import type { AppointmentStatus, AppointmentType, UserRole } from "@axyscare/core-types";

export const documentTypes = ["cedula", "pasaporte", "dni", "otro"] as const;
export const sexOptions = ["femenino", "masculino", "intersexual", "no_especificado"] as const;
export const genderOptions = ["mujer", "hombre", "no_binario", "prefiere_no_decir"] as const;

export const specialties = [
  "Medicina general",
  "Enfermería clínica",
  "Psicología clínica",
  "Nutrición clínica",
  "Nutrición deportiva",
  "Nutrición pediátrica",
  "Nutrición renal",
  "Nutrición oncológica",
  "Pediatría",
  "Ginecología",
  "Medicina interna",
  "Cardiología",
  "Medicina familiar",
  "Emergencias",
  "Salud mental",
] as const;

export const appointmentTypes: AppointmentType[] = [
  "presencial",
  "teleconsulta",
  "control",
  "procedimiento",
  "curacion",
  "valoracion_enfermeria",
  "visita_domiciliaria",
];

export const appointmentStatuses: AppointmentStatus[] = [
  "programada",
  "confirmada",
  "atendida",
  "cancelada",
  "no_asistio",
];

export type DiagnosisCatalogEntry = {
  code: string;
  label: string;
  audience: UserRole[];
};

export type ExamCatalogEntry = {
  category: "laboratorio" | "imagen" | "estudio_especial";
  label: string;
  panel?: string;
};

export type MedicationCatalogEntry = {
  name: string;
  presentation: string;
  commonDose?: string;
};

export const nursingBasicMedicationNames = [
  "Paracetamol",
  "Ibuprofeno",
  "Diclofenaco",
  "Naproxeno",
  "Ketorolaco",
  "Loratadina",
  "Cetirizina",
  "Omeprazol",
  "Metoclopramida",
  "Salbutamol",
  "Acetilcisteína",
  "Clorfenamina",
] as const;

export type NursingCareCatalogEntry = {
  id: string;
  label: string;
  outcomes: string[];
  interventions: string[];
  signs?: string[];
};

export const examCatalog: ExamCatalogEntry[] = [
  { category: "laboratorio", panel: "hematologia", label: "Biometría hemática completa" },
  { category: "laboratorio", panel: "hematologia", label: "Velocidad de eritrosedimentación" },
  { category: "laboratorio", panel: "hematologia", label: "Proteína C reactiva" },
  { category: "laboratorio", panel: "quimica", label: "Glucosa basal" },
  { category: "laboratorio", panel: "quimica", label: "Hemoglobina glicosilada" },
  { category: "laboratorio", panel: "quimica", label: "Perfil lipídico" },
  { category: "laboratorio", panel: "quimica", label: "Urea y creatinina" },
  { category: "laboratorio", panel: "quimica", label: "Electrolitos séricos" },
  { category: "laboratorio", panel: "hepatico", label: "Perfil hepático" },
  { category: "laboratorio", panel: "endocrino", label: "TSH" },
  { category: "laboratorio", panel: "endocrino", label: "T4 libre" },
  { category: "laboratorio", panel: "orina", label: "Uroanálisis" },
  { category: "laboratorio", panel: "orina", label: "Urocultivo" },
  { category: "laboratorio", panel: "microbiologia", label: "Coprológico" },
  { category: "laboratorio", panel: "microbiologia", label: "Coprocultivo" },
  { category: "laboratorio", panel: "microbiologia", label: "Prueba rápida de influenza" },
  { category: "laboratorio", panel: "microbiologia", label: "Prueba rápida de COVID-19" },
  { category: "laboratorio", panel: "cardiometabolico", label: "Troponina" },
  { category: "imagen", panel: "radiologia", label: "Radiografía de tórax" },
  { category: "imagen", panel: "radiologia", label: "Radiografía de extremidad" },
  { category: "imagen", panel: "radiologia", label: "Radiografía de columna" },
  { category: "imagen", panel: "ecografia", label: "Ecografía abdominal" },
  { category: "imagen", panel: "ecografia", label: "Ecografía pélvica" },
  { category: "imagen", panel: "ecografia", label: "Ecografía obstétrica" },
  { category: "imagen", panel: "tomografia", label: "Tomografía de cráneo" },
  { category: "imagen", panel: "tomografia", label: "Tomografía de tórax" },
  { category: "imagen", panel: "resonancia", label: "Resonancia magnética cerebral" },
  { category: "imagen", panel: "resonancia", label: "Resonancia magnética de columna" },
  { category: "estudio_especial", panel: "cardiologia", label: "Electrocardiograma" },
  { category: "estudio_especial", panel: "cardiologia", label: "Holter 24 horas" },
  { category: "estudio_especial", panel: "cardiologia", label: "Ecocardiograma" },
  { category: "estudio_especial", panel: "neumologia", label: "Espirometría" },
  { category: "estudio_especial", panel: "gastro", label: "Endoscopia digestiva alta" },
  { category: "estudio_especial", panel: "gastro", label: "Colonoscopia" },
  { category: "estudio_especial", panel: "neurologia", label: "Electroencefalograma" },
  { category: "estudio_especial", panel: "obstetricia", label: "Monitoreo fetal" },
];

export const frequentExams = examCatalog.slice(0, 10).map((item) => item.label);

export const frequentProcedures = [
  "Curación simple",
  "Curación avanzada",
  "Retiro de suturas",
  "Nebulización",
  "Canalización periférica",
  "Administración intramuscular",
  "Lavado de herida",
  "Sutura simple",
];

export const medicationCatalog: MedicationCatalogEntry[] = [
  // Analgesia, antiinflamatorios y corticoides
  { name: "Paracetamol", presentation: "Tableta 500 mg", commonDose: "1 tableta cada 8 horas" },
  { name: "Paracetamol", presentation: "Tableta 1 g", commonDose: "1 tableta cada 8 horas" },
  { name: "Paracetamol", presentation: "Suspensión 120 mg/5 ml", commonDose: "Según peso y edad" },
  { name: "Ibuprofeno", presentation: "Tableta 400 mg", commonDose: "1 tableta cada 8 horas con alimentos" },
  { name: "Ibuprofeno", presentation: "Tableta 600 mg", commonDose: "1 tableta cada 8 horas con alimentos" },
  { name: "Ibuprofeno", presentation: "Suspensión 100 mg/5 ml", commonDose: "Según peso y edad" },
  { name: "Diclofenaco", presentation: "Tableta 50 mg", commonDose: "1 tableta cada 8 horas" },
  { name: "Diclofenaco", presentation: "Ampolla 75 mg/3 ml", commonDose: "Según cuadro clínico" },
  { name: "Naproxeno", presentation: "Tableta 550 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Ketorolaco", presentation: "Tableta 10 mg", commonDose: "1 tableta cada 8 horas" },
  { name: "Ketorolaco", presentation: "Ampolla 30 mg/ml", commonDose: "Según dolor agudo" },
  { name: "Meloxicam", presentation: "Tableta 15 mg", commonDose: "1 tableta al día" },
  { name: "Celecoxib", presentation: "Cápsula 200 mg", commonDose: "1 cápsula cada 12 a 24 horas" },
  { name: "Prednisona", presentation: "Tableta 5 mg", commonDose: "Según esquema" },
  { name: "Prednisona", presentation: "Tableta 20 mg", commonDose: "Según esquema" },
  { name: "Dexametasona", presentation: "Tableta 4 mg", commonDose: "Según prescripción" },
  { name: "Dexametasona", presentation: "Ampolla 4 mg/ml", commonDose: "Según prescripción" },
  { name: "Hidrocortisona", presentation: "Crema 1%", commonDose: "Aplicar 2 veces al día" },
  { name: "Hidrocortisona", presentation: "Ampolla 100 mg", commonDose: "Según indicación médica" },

  // Antibióticos y antimicrobianos
  { name: "Amoxicilina", presentation: "Cápsula 500 mg", commonDose: "1 cápsula cada 8 horas" },
  { name: "Amoxicilina", presentation: "Suspensión 250 mg/5 ml", commonDose: "Según prescripción" },
  { name: "Amoxicilina + ácido clavulánico", presentation: "Tableta 875/125 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Amoxicilina + ácido clavulánico", presentation: "Suspensión 400/57 mg/5 ml", commonDose: "Según peso y edad" },
  { name: "Ampicilina", presentation: "Cápsula 500 mg", commonDose: "1 cápsula cada 6 horas" },
  { name: "Ampicilina", presentation: "Ampolla 1 g", commonDose: "Según indicación médica" },
  { name: "Azitromicina", presentation: "Tableta 500 mg", commonDose: "1 tableta al día" },
  { name: "Azitromicina", presentation: "Suspensión 200 mg/5 ml", commonDose: "Según peso y edad" },
  { name: "Cefalexina", presentation: "Cápsula 500 mg", commonDose: "1 cápsula cada 6 horas" },
  { name: "Cefalexina", presentation: "Suspensión 250 mg/5 ml", commonDose: "Según prescripción" },
  { name: "Cefixima", presentation: "Tableta 400 mg", commonDose: "1 tableta al día" },
  { name: "Cefixima", presentation: "Suspensión 100 mg/5 ml", commonDose: "Según peso y edad" },
  { name: "Ceftriaxona", presentation: "Vial 1 g", commonDose: "Según prescripción" },
  { name: "Cefuroxima", presentation: "Tableta 500 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Claritromicina", presentation: "Tableta 500 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Claritromicina", presentation: "Suspensión 250 mg/5 ml", commonDose: "Según prescripción" },
  { name: "Clindamicina", presentation: "Cápsula 300 mg", commonDose: "1 cápsula cada 8 horas" },
  { name: "Clindamicina", presentation: "Ampolla 600 mg/4 ml", commonDose: "Según indicación médica" },
  { name: "Ciprofloxacino", presentation: "Tableta 500 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Ciprofloxacino", presentation: "Solución IV 200 mg/100 ml", commonDose: "Según indicación médica" },
  { name: "Dicloxacilina", presentation: "Cápsula 500 mg", commonDose: "1 cápsula cada 6 horas" },
  { name: "Doxiciclina", presentation: "Cápsula 100 mg", commonDose: "1 cápsula cada 12 horas" },
  { name: "Levofloxacino", presentation: "Tableta 500 mg", commonDose: "1 tableta al día" },
  { name: "Metronidazol", presentation: "Tableta 500 mg", commonDose: "1 tableta cada 8 horas" },
  { name: "Metronidazol", presentation: "Suspensión 250 mg/5 ml", commonDose: "Según prescripción" },
  { name: "Metronidazol", presentation: "Solución IV 500 mg/100 ml", commonDose: "Según indicación médica" },
  { name: "Nitrofurantoína", presentation: "Cápsula 100 mg", commonDose: "1 cápsula cada 12 horas" },
  { name: "Nitrofurantoína", presentation: "Suspensión 25 mg/5 ml", commonDose: "Según prescripción" },
  { name: "Trimetoprim sulfametoxazol", presentation: "Tableta 160/800 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Trimetoprim sulfametoxazol", presentation: "Suspensión 40/200 mg/5 ml", commonDose: "Según peso y edad" },

  // Antifúngicos, antivirales y antiparasitarios
  { name: "Aciclovir", presentation: "Tableta 400 mg", commonDose: "1 tableta 5 veces al día según esquema" },
  { name: "Aciclovir", presentation: "Crema 5%", commonDose: "Aplicar 5 veces al día" },
  { name: "Albendazol", presentation: "Tableta 400 mg", commonDose: "Dosis única según indicación" },
  { name: "Albendazol", presentation: "Suspensión 200 mg/5 ml", commonDose: "Según peso y edad" },
  { name: "Clotrimazol", presentation: "Crema 1%", commonDose: "Aplicar cada 12 horas" },
  { name: "Clotrimazol", presentation: "Óvulo vaginal 500 mg", commonDose: "1 óvulo según esquema" },
  { name: "Fluconazol", presentation: "Cápsula 150 mg", commonDose: "Dosis única o semanal según indicación" },
  { name: "Ketoconazol", presentation: "Tableta 200 mg", commonDose: "Según indicación médica" },
  { name: "Ketoconazol", presentation: "Shampoo 2%", commonDose: "Aplicar 2 a 3 veces por semana" },
  { name: "Mebendazol", presentation: "Tableta 100 mg", commonDose: "Según esquema antiparasitario" },
  { name: "Mebendazol", presentation: "Suspensión 100 mg/5 ml", commonDose: "Según peso y edad" },
  { name: "Mupirocina", presentation: "Ungüento 2%", commonDose: "Aplicar 2 a 3 veces al día" },
  { name: "Nistatina", presentation: "Suspensión oral 100000 UI/ml", commonDose: "Según indicación médica" },
  { name: "Nistatina", presentation: "Crema 100000 UI/g", commonDose: "Aplicar 2 veces al día" },

  // Respiratorio y alergias
  { name: "Acetilcisteína", presentation: "Sobre 600 mg", commonDose: "1 sobre al día" },
  { name: "Acetilcisteína", presentation: "Jarabe 100 mg/5 ml", commonDose: "Según prescripción" },
  { name: "Ambroxol", presentation: "Jarabe 30 mg/5 ml", commonDose: "10 ml cada 8 horas" },
  { name: "Ambroxol", presentation: "Tableta 30 mg", commonDose: "1 tableta cada 8 horas" },
  { name: "Budesonida", presentation: "Suspensión nebulizable 0.5 mg/2 ml", commonDose: "Según indicación médica" },
  { name: "Budesonida", presentation: "Inhalador 200 mcg", commonDose: "1 a 2 inhalaciones cada 12 horas" },
  { name: "Cetirizina", presentation: "Tableta 10 mg", commonDose: "1 tableta al día" },
  { name: "Cetirizina", presentation: "Jarabe 5 mg/5 ml", commonDose: "Según peso y edad" },
  { name: "Clorfenamina", presentation: "Tableta 4 mg", commonDose: "1 tableta cada 8 horas" },
  { name: "Clorfenamina", presentation: "Jarabe 2 mg/5 ml", commonDose: "Según prescripción" },
  { name: "Desloratadina", presentation: "Tableta 5 mg", commonDose: "1 tableta al día" },
  { name: "Desloratadina", presentation: "Jarabe 2.5 mg/5 ml", commonDose: "Según peso y edad" },
  { name: "Fluticasona", presentation: "Spray nasal 50 mcg", commonDose: "1 a 2 disparos por fosa al día" },
  { name: "Loratadina", presentation: "Tableta 10 mg", commonDose: "1 tableta al día" },
  { name: "Loratadina", presentation: "Jarabe 5 mg/5 ml", commonDose: "Según peso y edad" },
  { name: "Montelukast", presentation: "Tableta 10 mg", commonDose: "1 tableta en la noche" },
  { name: "Montelukast", presentation: "Tableta masticable 4 mg", commonDose: "Según peso y edad" },
  { name: "Salbutamol", presentation: "Inhalador 100 mcg", commonDose: "2 puff según necesidad" },
  { name: "Salbutamol", presentation: "Solución nebulizable 5 mg/ml", commonDose: "Según indicación médica" },
  { name: "Salbutamol", presentation: "Jarabe 2 mg/5 ml", commonDose: "Según prescripción" },

  // Gastrointestinal
  { name: "Hidróxido de aluminio + magnesio", presentation: "Suspensión oral", commonDose: "10 ml después de comidas" },
  { name: "Lactulosa", presentation: "Jarabe 667 mg/ml", commonDose: "15 a 30 ml al día" },
  { name: "Loperamida", presentation: "Cápsula 2 mg", commonDose: "Según cuadro clínico" },
  { name: "Metoclopramida", presentation: "Tableta 10 mg", commonDose: "1 tableta cada 8 horas" },
  { name: "Metoclopramida", presentation: "Ampolla 10 mg/2 ml", commonDose: "Según indicación médica" },
  { name: "Omeprazol", presentation: "Cápsula 20 mg", commonDose: "1 cápsula antes del desayuno" },
  { name: "Omeprazol", presentation: "Cápsula 40 mg", commonDose: "1 cápsula al día" },
  { name: "Ondansetrón", presentation: "Tableta 8 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Ondansetrón", presentation: "Ampolla 4 mg/2 ml", commonDose: "Según indicación médica" },
  { name: "Pantoprazol", presentation: "Tableta 40 mg", commonDose: "1 tableta al día" },
  { name: "Pantoprazol", presentation: "Vial 40 mg", commonDose: "Según indicación médica" },
  { name: "Polietilenglicol", presentation: "Sobre 17 g", commonDose: "1 sobre al día" },
  { name: "Sales de rehidratación oral", presentation: "Sobre", commonDose: "Según pérdidas y tolerancia" },
  { name: "Sucralfato", presentation: "Tableta 1 g", commonDose: "1 tableta antes de comidas" },
  { name: "Sucralfato", presentation: "Suspensión 1 g/10 ml", commonDose: "10 ml antes de comidas" },
  { name: "Butilhioscina", presentation: "Tableta 10 mg", commonDose: "1 tableta cada 8 horas" },
  { name: "Butilhioscina", presentation: "Ampolla 20 mg/ml", commonDose: "Según indicación médica" },

  // Cardiometabólico
  { name: "AAS", presentation: "Tableta 100 mg", commonDose: "1 tableta al día" },
  { name: "AAS", presentation: "Tableta 500 mg", commonDose: "1 tableta cada 8 horas según necesidad" },
  { name: "Amlodipino", presentation: "Tableta 5 mg", commonDose: "1 tableta al día" },
  { name: "Amlodipino", presentation: "Tableta 10 mg", commonDose: "1 tableta al día" },
  { name: "Atenolol", presentation: "Tableta 50 mg", commonDose: "1 tableta al día" },
  { name: "Atorvastatina", presentation: "Tableta 20 mg", commonDose: "1 tableta en la noche" },
  { name: "Atorvastatina", presentation: "Tableta 40 mg", commonDose: "1 tableta en la noche" },
  { name: "Bisoprolol", presentation: "Tableta 5 mg", commonDose: "1 tableta al día" },
  { name: "Carvedilol", presentation: "Tableta 6.25 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Carvedilol", presentation: "Tableta 25 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Clopidogrel", presentation: "Tableta 75 mg", commonDose: "1 tableta al día" },
  { name: "Enalapril", presentation: "Tableta 5 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Enalapril", presentation: "Tableta 10 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Enalapril", presentation: "Tableta 20 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Espironolactona", presentation: "Tableta 25 mg", commonDose: "1 tableta al día" },
  { name: "Furosemida", presentation: "Tableta 40 mg", commonDose: "1 tableta al día" },
  { name: "Furosemida", presentation: "Ampolla 20 mg/2 ml", commonDose: "Según indicación médica" },
  { name: "Hidroclorotiazida", presentation: "Tableta 25 mg", commonDose: "1 tableta al día" },
  { name: "Losartán", presentation: "Tableta 50 mg", commonDose: "1 tableta al día" },
  { name: "Losartán", presentation: "Tableta 100 mg", commonDose: "1 tableta al día" },
  { name: "Metoprolol", presentation: "Tableta 50 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Nifedipino", presentation: "Tableta 30 mg", commonDose: "1 tableta al día" },
  { name: "Rosuvastatina", presentation: "Tableta 10 mg", commonDose: "1 tableta en la noche" },
  { name: "Rosuvastatina", presentation: "Tableta 20 mg", commonDose: "1 tableta en la noche" },

  // Endocrino y diabetes
  { name: "Glibenclamida", presentation: "Tableta 5 mg", commonDose: "1 tableta al día o cada 12 horas" },
  { name: "Gliclazida", presentation: "Tableta 30 mg", commonDose: "1 tableta al día" },
  { name: "Insulina glargina", presentation: "Pluma 100 UI/ml", commonDose: "Según control glucémico" },
  { name: "Insulina NPH", presentation: "Frasco 100 UI/ml", commonDose: "Según control glucémico" },
  { name: "Insulina regular", presentation: "Frasco 100 UI/ml", commonDose: "Según control glucémico" },
  { name: "Levotiroxina", presentation: "Tableta 50 mcg", commonDose: "1 tableta en ayunas" },
  { name: "Levotiroxina", presentation: "Tableta 100 mcg", commonDose: "1 tableta en ayunas" },
  { name: "Metformina", presentation: "Tableta 500 mg", commonDose: "1 tableta cada 12 horas con alimentos" },
  { name: "Metformina", presentation: "Tableta 850 mg", commonDose: "1 tableta cada 12 horas" },
  { name: "Metformina", presentation: "Tableta 1 g", commonDose: "1 tableta cada 12 horas" },
  { name: "Metimazol", presentation: "Tableta 5 mg", commonDose: "Según control tiroideo" },
  { name: "Sitagliptina", presentation: "Tableta 100 mg", commonDose: "1 tableta al día" },

  // Salud mental y neurología
  { name: "Alprazolam", presentation: "Tableta 0.5 mg", commonDose: "Según indicación médica" },
  { name: "Alprazolam", presentation: "Tableta 1 mg", commonDose: "Según indicación médica" },
  { name: "Amitriptilina", presentation: "Tableta 25 mg", commonDose: "1 tableta en la noche" },
  { name: "Clonazepam", presentation: "Tableta 0.5 mg", commonDose: "Según indicación médica" },
  { name: "Clonazepam", presentation: "Tableta 2 mg", commonDose: "Según indicación médica" },
  { name: "Diazepam", presentation: "Tableta 5 mg", commonDose: "Según indicación médica" },
  { name: "Diazepam", presentation: "Ampolla 10 mg/2 ml", commonDose: "Según indicación médica" },
  { name: "Escitalopram", presentation: "Tableta 10 mg", commonDose: "1 tableta al día" },
  { name: "Escitalopram", presentation: "Tableta 20 mg", commonDose: "1 tableta al día" },
  { name: "Fluoxetina", presentation: "Cápsula 20 mg", commonDose: "1 cápsula al día" },
  { name: "Quetiapina", presentation: "Tableta 25 mg", commonDose: "Según indicación médica" },
  { name: "Quetiapina", presentation: "Tableta 100 mg", commonDose: "Según indicación médica" },
  { name: "Risperidona", presentation: "Tableta 1 mg", commonDose: "Según indicación médica" },
  { name: "Risperidona", presentation: "Tableta 2 mg", commonDose: "Según indicación médica" },
  { name: "Sertralina", presentation: "Tableta 50 mg", commonDose: "1 tableta al día" },
  { name: "Sertralina", presentation: "Tableta 100 mg", commonDose: "1 tableta al día" },

  // Ginecología, urología y suplementos
  { name: "Ácido fólico", presentation: "Tableta 1 mg", commonDose: "1 tableta al día" },
  { name: "Calcio + vitamina D", presentation: "Tableta", commonDose: "1 tableta al día" },
  { name: "Nitrofurazona", presentation: "Crema 0.2%", commonDose: "Aplicar según curación" },
  { name: "Sulfato ferroso", presentation: "Tableta 300 mg", commonDose: "1 tableta al día" },
  { name: "Sulfato ferroso", presentation: "Jarabe 125 mg/5 ml", commonDose: "Según prescripción" },
  { name: "Óvulos de metronidazol + nistatina", presentation: "Óvulo vaginal", commonDose: "1 óvulo por noche según esquema" },
  { name: "Zinc", presentation: "Tableta 20 mg", commonDose: "1 tableta al día" },
];

export const frequentMedications = Array.from(
  new Set(medicationCatalog.map((item) => item.name)),
);

export const icd10Catalog: DiagnosisCatalogEntry[] = [
  { code: "J06.9", label: "Infección aguda de vías respiratorias superiores, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "I10", label: "Hipertensión esencial primaria", audience: ["medico", "profesional_mixto"] },
  { code: "E11.9", label: "Diabetes mellitus tipo 2 sin complicaciones", audience: ["medico", "profesional_mixto"] },
  { code: "N39.0", label: "Infección de vías urinarias, sitio no especificado", audience: ["medico", "profesional_mixto"] },
  { code: "M54.5", label: "Lumbalgia", audience: ["medico", "profesional_mixto"] },
  { code: "R50.9", label: "Fiebre, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "K29.7", label: "Gastritis, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "A09.9", label: "Gastroenteritis y colitis de origen infeccioso no especificado", audience: ["medico", "profesional_mixto"] },
  { code: "J45.9", label: "Asma, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "F41.1", label: "Trastorno de ansiedad generalizada", audience: ["medico", "profesional_mixto", "psicologo"] },
  { code: "J02.9", label: "Faringitis aguda, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "J03.9", label: "Amigdalitis aguda, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "J18.9", label: "Neumonía, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "J20.9", label: "Bronquitis aguda, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "J44.9", label: "Enfermedad pulmonar obstructiva crónica, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "J01.9", label: "Sinusitis aguda, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "J30.4", label: "Rinitis alérgica, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "R05", label: "Tos", audience: ["medico", "profesional_mixto"] },
  { code: "R06.0", label: "Disnea", audience: ["medico", "profesional_mixto"] },
  { code: "R07.4", label: "Dolor torácico, no especificado", audience: ["medico", "profesional_mixto"] },
  { code: "K21.9", label: "Enfermedad por reflujo gastroesofágico sin esofagitis", audience: ["medico", "profesional_mixto"] },
  { code: "K52.9", label: "Gastroenteritis y colitis no infecciosa, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "K30", label: "Dispepsia funcional", audience: ["medico", "profesional_mixto"] },
  { code: "K59.0", label: "Estreñimiento", audience: ["medico", "profesional_mixto"] },
  { code: "R10.4", label: "Otros dolores abdominales y los no especificados", audience: ["medico", "profesional_mixto"] },
  { code: "R11", label: "Náusea y vómito", audience: ["medico", "profesional_mixto"] },
  { code: "I11.9", label: "Enfermedad cardíaca hipertensiva sin insuficiencia cardíaca", audience: ["medico", "profesional_mixto"] },
  { code: "I25.9", label: "Enfermedad isquémica crónica del corazón, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "E78.5", label: "Hiperlipidemia, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "E66.9", label: "Obesidad, no especificada", audience: ["medico", "profesional_mixto", "nutricion"] },
  { code: "E03.9", label: "Hipotiroidismo, no especificado", audience: ["medico", "profesional_mixto"] },
  { code: "E05.9", label: "Tirotoxicosis, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "M79.1", label: "Mialgia", audience: ["medico", "profesional_mixto"] },
  { code: "M25.5", label: "Dolor en articulación", audience: ["medico", "profesional_mixto"] },
  { code: "M54.2", label: "Cervicalgia", audience: ["medico", "profesional_mixto"] },
  { code: "M17.9", label: "Gonartrosis, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "M51.1", label: "Trastornos de discos lumbares con radiculopatía", audience: ["medico", "profesional_mixto"] },
  { code: "N76.0", label: "Vaginitis aguda", audience: ["medico", "profesional_mixto"] },
  { code: "N30.0", label: "Cistitis aguda", audience: ["medico", "profesional_mixto"] },
  { code: "N40", label: "Hiperplasia de la próstata", audience: ["medico", "profesional_mixto"] },
  { code: "R35.0", label: "Poliuria", audience: ["medico", "profesional_mixto"] },
  { code: "L20.9", label: "Dermatitis atópica, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "L23.9", label: "Dermatitis alérgica de contacto, causa no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "L30.9", label: "Dermatitis, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "L70.0", label: "Acné vulgar", audience: ["medico", "profesional_mixto"] },
  { code: "B35.3", label: "Tiña del pie", audience: ["medico", "profesional_mixto"] },
  { code: "B37.3", label: "Candidiasis de la vulva y de la vagina", audience: ["medico", "profesional_mixto"] },
  { code: "G43.9", label: "Migraña, no especificada", audience: ["medico", "profesional_mixto"] },
  { code: "R51", label: "Cefalea", audience: ["medico", "profesional_mixto"] },
  { code: "G47.0", label: "Trastornos del inicio y del mantenimiento del sueño", audience: ["medico", "profesional_mixto", "psicologo"] },
  { code: "F32.9", label: "Episodio depresivo, no especificado", audience: ["medico", "profesional_mixto", "psicologo"] },
  { code: "F33.1", label: "Trastorno depresivo recurrente, episodio actual moderado", audience: ["medico", "profesional_mixto", "psicologo"] },
  { code: "F41.0", label: "Trastorno de pánico", audience: ["medico", "profesional_mixto", "psicologo"] },
  { code: "F43.2", label: "Trastornos de adaptación", audience: ["medico", "profesional_mixto", "psicologo"] },
  { code: "F90.0", label: "Trastorno de la actividad y de la atención", audience: ["medico", "profesional_mixto", "psicologo"] },
  { code: "Z00.0", label: "Examen médico general", audience: ["medico", "profesional_mixto"] },
  { code: "Z71.3", label: "Consejo y vigilancia dietéticos", audience: ["medico", "profesional_mixto", "nutricion"] },
  { code: "Z72.0", label: "Problemas relacionados con el uso del tabaco", audience: ["medico", "profesional_mixto", "psicologo"] },
  { code: "Z76.0", label: "Repetición de receta", audience: ["medico", "profesional_mixto"] },
];

export const psychologyCatalog = [
  {
    code: "PSY-ANX",
    label: "Síntomas compatibles con ansiedad clínica",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "PSY-DEP",
    label: "Síntomas compatibles con episodio depresivo",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "PSY-INS",
    label: "Alteración del sueño con impacto funcional",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "PSY-STR",
    label: "Respuesta clínica asociada a estrés agudo",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-GAD",
    label: "Trastorno de ansiedad generalizada",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-PD",
    label: "Trastorno de pánico",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-SAD",
    label: "Trastorno de ansiedad social",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-SPF",
    label: "Fobia específica",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-OCD",
    label: "Trastorno obsesivo-compulsivo",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-PTSD",
    label: "Trastorno de estrés postraumático",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-ASD",
    label: "Trastorno por estrés agudo",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-ADJ",
    label: "Trastorno de adaptación",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-MDD",
    label: "Trastorno depresivo mayor",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-PDD",
    label: "Trastorno depresivo persistente (distimia)",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-BD1",
    label: "Trastorno bipolar tipo I",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-BD2",
    label: "Trastorno bipolar tipo II",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-INS",
    label: "Trastorno de insomnio",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-ADHD",
    label: "Trastorno por déficit de atención e hiperactividad",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-AUT",
    label: "Trastorno del espectro autista",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-ODD",
    label: "Trastorno negativista desafiante",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-CD",
    label: "Trastorno de conducta",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-AN",
    label: "Anorexia nerviosa",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-BN",
    label: "Bulimia nerviosa",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-BED",
    label: "Trastorno por atracón",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-SUD-ALC",
    label: "Trastorno por consumo de alcohol",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-SUD-NIC",
    label: "Trastorno por consumo de tabaco",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-SCZ",
    label: "Esquizofrenia",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-SCHAF",
    label: "Trastorno esquizoafectivo",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-BPD",
    label: "Trastorno límite de la personalidad",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-AVPD",
    label: "Trastorno de personalidad evitativa",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
  {
    code: "DSM5-OCPD",
    label: "Trastorno obsesivo-compulsivo de la personalidad",
    audience: ["psicologo", "profesional_mixto"] as UserRole[],
  },
] as const;

export const nutritionCatalog = [
  {
    code: "NUT-OB1",
    label: "Exceso de ingesta energética con objetivo de reducción ponderal",
    audience: ["nutricion", "profesional_mixto"] as UserRole[],
  },
  {
    code: "NUT-DM2",
    label: "Plan de alimentación para diabetes mellitus tipo 2",
    audience: ["nutricion", "profesional_mixto"] as UserRole[],
  },
  {
    code: "NUT-DLP",
    label: "Intervención nutricional para dislipidemia",
    audience: ["nutricion", "profesional_mixto"] as UserRole[],
  },
  {
    code: "NUT-HTA",
    label: "Manejo dietético para hipertensión arterial",
    audience: ["nutricion", "profesional_mixto"] as UserRole[],
  },
  {
    code: "NUT-SGI",
    label: "Orientación nutricional para síntomas gastrointestinales",
    audience: ["nutricion", "profesional_mixto"] as UserRole[],
  },
] as const;

export const internalNursingSuggestionCatalog: NursingCareCatalogEntry[] = [
  {
    id: "hydration-risk",
    label: "Riesgo de hidratación insuficiente",
    signs: ["Mucosas secas", "Baja ingesta oral", "Balance hídrico negativo"],
    outcomes: ["Balance hídrico estable", "Mucosas hidratadas"],
    interventions: ["Monitorizar ingesta", "Reforzar hidratación oral"],
  },
  {
    id: "acute-pain-watch",
    label: "Dolor agudo en observación",
    signs: ["Escala de dolor elevada", "Gestos de dolor", "Limitación funcional"],
    outcomes: ["Disminución del dolor", "Mayor confort"],
    interventions: ["Revalorar escala de dolor", "Aplicar medidas de alivio"],
  },
  {
    id: "oxygenation-watch",
    label: "Vigilancia de oxigenación comprometida",
    signs: ["SatO2 disminuida", "Disnea", "Trabajo respiratorio aumentado"],
    outcomes: ["Saturación estable", "Trabajo respiratorio adecuado"],
    interventions: ["Control de saturación", "Valorar necesidad de derivación"],
  },
  {
    id: "skin-integrity-risk",
    label: "Riesgo de deterioro de la integridad cutánea",
    signs: ["Herida activa", "Curación repetida", "Movilidad limitada"],
    outcomes: ["Piel íntegra", "Herida en proceso de cicatrización"],
    interventions: ["Valorar bordes y exudado", "Mantener técnica aséptica"],
  },
  {
    id: "acute-pain",
    label: "Dolor agudo",
    signs: ["Verbalización de dolor", "Expresión facial de dolor", "Protectividad corporal"],
    outcomes: ["Control del dolor", "Confort físico mejorado", "Participación en el cuidado"],
    interventions: ["Valorar intensidad y características del dolor", "Aplicar medidas no farmacológicas", "Administrar analgesia según indicación"],
  },
  {
    id: "impaired-gas-exchange",
    label: "Intercambio gaseoso deteriorado",
    signs: ["Disnea", "SatO2 disminuida", "Uso de músculos accesorios"],
    outcomes: ["Oxigenación tisular adecuada", "Patrón respiratorio eficaz", "Saturación dentro de meta"],
    interventions: ["Monitorizar saturación y FR", "Posicionar para favorecer expansión pulmonar", "Coordinar oxigenoterapia según indicación"],
  },
  {
    id: "ineffective-airway-clearance",
    label: "Limpieza ineficaz de las vías aéreas",
    signs: ["Tos inefectiva", "Secreciones retenidas", "Ruidos respiratorios adventicios"],
    outcomes: ["Vía aérea permeable", "Eliminación eficaz de secreciones"],
    interventions: ["Favorecer hidratación", "Enseñar técnica de tos efectiva", "Vigilar esfuerzo respiratorio"],
  },
  {
    id: "hyperthermia",
    label: "Hipertermia",
    signs: ["Temperatura elevada", "Piel caliente", "Malestar general"],
    outcomes: ["Temperatura dentro de rango", "Confort térmico restaurado"],
    interventions: ["Monitorizar temperatura", "Favorecer medidas físicas de enfriamiento", "Vigilar respuesta a tratamiento"],
  },
  {
    id: "risk-infection",
    label: "Riesgo de infección",
    signs: ["Procedimiento invasivo", "Herida activa", "Enfermedad crónica"],
    outcomes: ["Ausencia de signos de infección", "Integridad tisular preservada"],
    interventions: ["Mantener técnica aséptica", "Educar signos de alarma", "Vigilar sitio de acceso o herida"],
  },
  {
    id: "impaired-skin-integrity",
    label: "Deterioro de la integridad cutánea",
    signs: ["Lesión cutánea", "Eritema", "Pérdida de continuidad de la piel"],
    outcomes: ["Cicatrización de la herida", "Integridad tisular mejorada"],
    interventions: ["Valorar tamaño y características de la lesión", "Realizar curación protocolizada", "Proteger piel perilesional"],
  },
  {
    id: "activity-intolerance",
    label: "Intolerancia a la actividad",
    signs: ["Fatiga al esfuerzo", "Disnea con actividad", "Debilidad referida"],
    outcomes: ["Tolerancia a la actividad mejorada", "Energía conservada"],
    interventions: ["Dosificar actividad y reposo", "Monitorizar respuesta hemodinámica", "Promover progresión gradual"],
  },
  {
    id: "fatigue",
    label: "Fatiga",
    signs: ["Cansancio persistente", "Bajo rendimiento funcional", "Somnolencia"],
    outcomes: ["Nivel de energía mejorado", "Rutina de descanso adecuada"],
    interventions: ["Identificar factores desencadenantes", "Planificar periodos de descanso", "Reforzar higiene del sueño"],
  },
  {
    id: "anxiety-nursing",
    label: "Ansiedad",
    signs: ["Inquietud", "Expresión de temor", "Taquicardia situacional"],
    outcomes: ["Ansiedad disminuida", "Afrontamiento eficaz"],
    interventions: ["Brindar información clara", "Favorecer técnicas de respiración y relajación", "Escucha activa"],
  },
  {
    id: "sleep-pattern-disturbance",
    label: "Trastorno del patrón del sueño",
    signs: ["Dificultad para conciliar sueño", "Despertares frecuentes", "Somnolencia diurna"],
    outcomes: ["Sueño reparador", "Descanso adecuado"],
    interventions: ["Promover higiene del sueño", "Reducir estímulos ambientales", "Educar rutina nocturna"],
  },
  {
    id: "nausea",
    label: "Náuseas",
    signs: ["Malestar gástrico", "Arcadas", "Disminución de ingesta"],
    outcomes: ["Náuseas controladas", "Tolerancia oral conservada"],
    interventions: ["Valorar desencadenantes", "Fraccionar ingesta según tolerancia", "Monitorizar hidratación"],
  },
  {
    id: "diarrhea",
    label: "Diarrea",
    signs: ["Deposiciones líquidas frecuentes", "Urgencia fecal", "Dolor abdominal"],
    outcomes: ["Patrón intestinal estabilizado", "Balance hídrico adecuado"],
    interventions: ["Registrar frecuencia y características", "Vigilar signos de deshidratación", "Educar dieta astringente si aplica"],
  },
  {
    id: "constipation",
    label: "Estreñimiento",
    signs: ["Disminución de frecuencia evacuatoria", "Heces duras", "Esfuerzo al evacuar"],
    outcomes: ["Eliminación intestinal eficaz", "Confort abdominal"],
    interventions: ["Favorecer hidratación", "Promover actividad física según tolerancia", "Educar ingesta de fibra"],
  },
  {
    id: "risk-falls",
    label: "Riesgo de caídas",
    signs: ["Marcha inestable", "Mareo", "Uso de fármacos sedantes"],
    outcomes: ["Ausencia de caídas", "Seguridad física mantenida"],
    interventions: ["Valorar riesgo de caídas", "Asegurar entorno seguro", "Educar medidas preventivas"],
  },
  {
    id: "impaired-urinary-elimination",
    label: "Deterioro de la eliminación urinaria",
    signs: ["Disuria", "Polaquiuria", "Retención urinaria"],
    outcomes: ["Patrón urinario mejorado", "Confort urinario"],
    interventions: ["Registrar patrón urinario", "Favorecer ingesta hídrica si procede", "Identificar signos de alarma"],
  },
  {
    id: "self-care-deficit",
    label: "Déficit de autocuidado",
    signs: ["Dependencia para higiene", "Limitación funcional", "Baja adherencia"],
    outcomes: ["Autocuidado progresivamente independiente", "Participación activa del paciente"],
    interventions: ["Valorar capacidad funcional", "Enseñar actividades adaptadas", "Involucrar red de apoyo"],
  },
  {
    id: "ineffective-health-management",
    label: "Manejo ineficaz de la salud",
    signs: ["Baja adherencia terapéutica", "Conocimiento insuficiente", "Reingresos frecuentes"],
    outcomes: ["Adherencia al plan de cuidados", "Conocimiento del régimen terapéutico"],
    interventions: ["Educar plan terapéutico", "Verificar comprensión del paciente", "Reforzar seguimiento y autocontrol"],
  },
  {
    id: "risk-unstable-glucose",
    label: "Riesgo de nivel de glucemia inestable",
    signs: ["Diabetes", "Ingesta irregular", "Uso de insulina o hipoglucemiantes"],
    outcomes: ["Glucemia dentro de metas", "Reconocimiento de signos de descompensación"],
    interventions: ["Monitorizar glucemia", "Educar sobre dieta y medicación", "Identificar signos de hipoglucemia e hiperglucemia"],
  },
  {
    id: "imbalanced-nutrition-less",
    label: "Nutrición desequilibrada: inferior a las necesidades corporales",
    signs: ["Pérdida de peso", "Baja ingesta", "Debilidad"],
    outcomes: ["Estado nutricional mejorado", "Ingesta adecuada"],
    interventions: ["Registrar ingesta", "Coordinar soporte nutricional", "Educar fraccionamiento y densidad calórica"],
  },
  {
    id: "caregiver-role-strain",
    label: "Sobrecarga del rol del cuidador",
    signs: ["Agotamiento", "Estrés del cuidador", "Dificultad para sostener cuidados"],
    outcomes: ["Bienestar del cuidador mejorado", "Apoyo social identificado"],
    interventions: ["Valorar carga del cuidador", "Facilitar redes de apoyo", "Educar autocuidado del cuidador"],
  },
] as const;
